version: 2
jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      - run: mkdir -p testing-apis-with-cypress/cypress/test-results testing-apis-with-cypress/cypress/test-results/screenshots
      - run: $(npm bin)/cypress run
      - store_test_results:
          path: testing-apis-with-cypress/cypress/test-results
      - store_artifacts:
          path: ~/repo/api-testing-with-cypress
      - store_artifacts:
          path: testing-apis-with-cypress/cypress/test-results/screenshots